### ISSUE TITLE
Want to contribute in improving this app

### ISSUE THREAD

**Issue by priyda** [maheshgurav/schoolapp#27]
Hi ,  I like this repository and the idea of it. do you need some help in adding some functionality to this app. 

I am looking to make some contribution. Let me know if you need some help

**Comment by maheshgurav** [comment]
Hi @priyda, thanks for your interest in this project. I am going to convert this application to spring-boot application. I will be creating a separate project for that. Will add some tasks there. It would be great if you can pick some tasks.
